__author__ = 'xw'

#coding:utf-8
kk={'additive1': 8.5, 'additive1Rate': 0, 'additive1Type': '', 'additive1factory': '', 'additive2': 0, 'additive2Rate': 0, 'additive2Type': '', 'additive2factory': '', 'additive3': 0, 'additive3Rate': 0, 'additive3Type': '', 'additive3factory': '', 'additive4': 0, 'additive4Rate': 0, 'additive4Type': '', 'additive4factory': '', 'additveOneModel': '', 'additveOneReportId': '', 'additveTwoModel': '', 'additveTwoReportId': '', 'admixtrue1': 85, 'admixtrue1Other': '', 'admixtrue1Rate': 0, 'admixtrue1factory': '', 'admixtrue1type': '', 'admixtrue2': 99, 'admixtrue2Other': '', 'admixtrue2Rate': 0, 'admixtrue2factory': '', 'admixtrue2type': '', 'admixtrue3': 0, 'admixtrue3Other': '', 'admixtrue3Rate': 0, 'admixtrue3factory': '', 'admixtrue3type': '', 'admixtruecount': '', 'admixtruepass': '0', 'alertJcjgId': '', 'alertValue': '', 'ash': 0, 'ashReportId': '', 'cement': 288, 'cementRate': 0, 'cementReportId': '', 'cementType': '', 'cementTypeOther': '', 'cementfactory': '', 'cityJcjgIds': '', 'code': '', 'concreteType': '', 'curPage': 1, 'endSql': ') row_ WHERE rownum<=20) WHERE rownum_>0', 'hntMixalert': '', 'hntjgPermissionId': '', 'hntpermissionIds': "'JC689397860'", 'imperviouSgrade': '', 'impervious': '0', 'inSpectInstituTionName': '华润混凝土（晋江）有限公司-停产', 'isBig': '1', 'isInsert': '', 'jcjgId': 'JC689397860', 'jgPermissionId': '', 'jgPermissionIds': '', 'jzpermissionIds': "'JC689397860'", 'logjcjgid': "'JC689397860'", 'lqPermissionIds': "'JC689397860'", 'mixGrade': 'C35', 'mixId': 'SP2017538', 'mixPid': '5627D11E4E4AEBC7E0536401A8C0421A', 'mixed': 0, 'mixedReportId': '', 'otherFourReportId': '', 'otherOneReportId': '', 'otherThreeReportId': '', 'otherTwoReportId': '', 'otheradmixtrue': '0', 'permissionIds': "'JC689397860'", 'reptpermissionids': "'JC689397860'", 'resultValue': '', 'sand': 721, 'sand2Type': '', 'sand3Type': '', 'sandMz': '', 'sandRate': 0, 'sandReportId': '', 'sandType': '', 'sandType2Other': '', 'sandType3Other': '', 'sandTypeOther': '', 'slag': 0, 'slagReportId': '', 'slump': '180-220', 'startSql': 'select  * from ( select row_.*,rownum as rownum_ from (', 'stone': 997, 'stone2Type': '', 'stone3Type': '', 'stoneGrainSize': '', 'stoneRate': 0, 'stoneReportId': '', 'stoneType': '', 'stoneType2Other': '', 'stoneType3Other': '', 'stoneTypeOther': '', 'tjcjgid': '', 'water': 170, 'waterRate': 0, 'zmixGrade': ''}

print(kk['zmixGrade'])



